steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "asia-southeast2-docker.pkg.dev/submissionmlgc-fauzan-427513/dockerml/model-image-last"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "asia-southeast2-docker.pkg.dev/submissionmlgc-fauzan-427513/dockerml/model-image-last"
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "api-service-backend"
      - "--image=asia-southeast2-docker.pkg.dev/submissionmlgc-fauzan-427513/dockerml/model-image-last"
      - "--region=us-central1"
      - "--cpu=1"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
images:
  - "asia-southeast2-docker.pkg.dev/submissionmlgc-fauzan-427513/dockerml/model-image-last"
